= {VertX} Redis Client

== Removal of request null argument

Redis does not accept `null` values in the request. The `Request#nullArg()` method therefore encoded `null` as the 4-character `"null"` string.

This method, which was deprecated in {v4x}, is removed. All places that used it to encode the `null` value now throw an `IllegalArgumentException`.

If you use `null` values in Redis requests, you should stop doing that. To restore previous behavior, you should encode `null` values as `"null"` manually. This applies to:

- `Request.arg(String)`
- `Request.arg(Buffer)`
- `Request.arg(JsonArray)`: both the array itself, and individual elements
- `Request.arg(JsonObject)`: both the object itself, and individual elements

== Automatic forwarding of Redis subscriptions to the Vert.x event bus

In {VertX} {v4x}, the Redis subscriptions were automatically forwarded to the event bus, unless the message handler was set explicitly (using `RedisConnection.handler()`).

This is no longer the case. Since {VertX5}, you always have to register a message handler. If you still want the subscription messages forwarded to the event bus, you have to manually create an instance of `EventBusHandler` and register it using `RedisConnection.handler()`:

[source,java]
----
RedisConnection conn = ...;
conn.handler(EventBusHandler.create(vertx));
conn.send(Request.cmd(Command.SUBSCRIBE).arg("news"));
----

In addition, the `EventBusHandler` does not forward only messages (`[p]message`); it also forwards subscriptions and un-subscriptions (`[p]subscribe` and `[p]unsubscribe`).

== RedisCluster.groupByNodes() changed return type + code generation changes

The `RedisCluster#groupByNodes()` method used to return `Future<List<List<Request>>>`. Due to this return type, the `RedisCluster` wasn't `@VertxGen`.

This has changed in {VertX5}. The `groupByNodes()` method now returns `Future<RequestGrouping>` and the entire interface is `@VertxGen`.

Further, the `Request`, `Response` and `Command` interfaces are no longer `@VertxGen` -- instead, they are `@DataObject`. This means that users of code-generated APIs (such as {VertX} Rx) will no longer use the generated wrappers; they will use the core Vert.x Redis interfaces.

== JSON serialization/deserialization of RedisOptions

The `RedisOptions` class has multiple methods to configure the Redis endpoints. These methods are still available, but the JSON format of this class has changed to only include one canonical field: `endpoints`.

If you rely on the JSON form of `RedisOptions` objects, note that the `endpoint`, `connectionString` and `connectionStrings` members of the JSON object are no longer recognized by the deserializer and are no longer generated by the serializer. Ensure that the necessary information is present in the `endpoints` member.
