= {VertX} Web

== RoutingContext user API

User related operations have been moved under a single context API accessible from `RoutingContext`

=== Logout

[source,java]
----
// 4.x
routingContext.clearUser();

// 5.0
UserContext userContext = routingContext.userContext();
userContext.logout();
----

=== Setting a user

The `RoutingContext#setUser` method has been removed, this operation should be performed by authentication handlers instead.

== Static handler configuration

`StaticHandler` methods `setAllowRootFileSystemAccess` and `setWebRoot` are removed after deprecation in {VertX} {v4x}.

Instead, the handler must be configured at creation time:

[source,java]
----
// 4.x
StaticHandler handler = StaticHandler.create().setAllowRootFileSystemAccess(true).setWebRoot(root);

// 5.0
StaticHandler handler = StaticHandler.create(FileSystemAccess.ROOT, root);
----

== Unwrapping a template engine

Template engine method to obtain the underlying engine instance have been removed after deprecation:

- `HandlebarsTemplateEngine#getHandlebars`
- `ThymeleafTemplateEngine#getThymeleafTemplateEngine`

Instead `TemplateEngine#unwrap` should be used:

[source,java]
----
// 4.x
Handlebars handlebarsUnwrapped = handlebarsTemplateEngine.getHandlebars();
TemplateEngine thymeleafUnwrapped = thymeleafTemplateEngine.getThymeleafTemplateEngine();

// 5.0
handlebarsUnwrapped = handlebarsTemplateEngine.unwrap();
thymeleafUnwrapped = thymeleafTemplateEngine.unwrap();
----

== CORS regex origins

The naming of regular expression origin(s) based methods are changed to be aligned with the rest of the framework

- `CorsHandler#addRelativeOrigin`
- `CorsHandler#addRelativeOrigins`

Instead the `addOriginWithRegex` or `addOriginsWithRegex` should be used:

[source,java]
----
// 4.x
CorsHandler.addRelativeOrigin(".*");
CorsHandler.addRelativeOrigins(List.of(".*", "https?://.*"));

// 5.0
CorsHandler.addOriginWithRegex(".*");
CorsHandler.addOriginsWithRegex(List.of(".*", "https?://.*"));
----
