= {VertX} Micrometer Metrics

== Upgrade to Micrometer 1.14

Micrometer 1.14 comes after 1.13, which is a breaking change release if you are using the PrometheusMeterRegistry API in your code.

Please take a look at Micrometer's https://github.com/micrometer-metrics/micrometer/wiki/1.13-Migration-Guide[migration guide].

== HTTP client pool metrics

HTTP client pool metrics are now exposed as generic pool metrics with pool type http

- `vertx_http_client_queue_pending` → `vertx_pool_queue_pending`
- `vertx_http_client_queue_time_seconds` → `vertx_pool_queue_time_seconds`

== Remove setting a registry on options

The micrometer options setter for a `MeterRegistry` has been removed in favour of the new `VertxBuilder` along with the `MicrometerMetricsFactory`.

[source,java]
----
// 4.x
Vertx vertx = Vertx.vertx(new VertxOptions()
 .setMetricsOptions(new MicrometerMetricsOptions()
   .setMicrometerRegistry(myRegistry)
   .setEnabled(true)));

// 5.0
Vertx vertx = Vertx.builder()
  .with(new VertxOptions()
    .setMetricsOptions(new MicrometerMetricsOptions()
    .setEnabled(true)))
  .withMetrics(new MicrometerMetricsFactory(myRegistry))
  .build();
----

== Remove InfluxDB options number of threads

`VertxInfluxDbOptions#getNumThreads` and `VertxInfluxDbOptions#setNumThreads` are no longer used.

[source,java]
----
// 4.x
influxDbOptions.setNumThreads(numThreads);

// 5.0
----

== Rename metrics options request tag provider

`VertxMicrometerMetricsOptions#setRequestTagsProvider` and `VertxMicrometerMetricsOptions#getRequestTagsProvider` are removed in favour of `VertxMicrometerMetricsOptions#setServerRequestTagsProvider` and `VertxMicrometerMetricsOptions#getServerRequestTagsProvider`.

[source,java]
----
// 4.x
options.setRequestsTagsProvider(provider);

// 5.0
options.setServerRequestsTagsProvider(provider);
----

== Changes in metrics tags enabled by default

The HTTP `ROUTE` tag is no longer enabled by default, due to high cardinality risk.

To enable it, you must modify the metrics options on startup:

[source,java]
----
options.addLabels(Label.HTTP_ROUTE);
----

The POOL `NAME` tag is now enabled by default.
